### ISSUE TITLE
CMake issue on macosx

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.core#4]
Hey guys, do you know how can I prevent travis from adding -mmacosx-version-min=10.6 to the [build command](https://travis-ci.org/conda-forge/staged-recipes/jobs/121629077#L489)? We are discussing it [here](https://github.com/conda-forge/staged-recipes/pull/288).

**Comment by siebenkopf** [comment]
I haven't used conda yet, so I don't know if there are any environment variables that are set in conda. However, I have seen that these kind of command line options (e.g., the ``-DNDEBUG`` flag is added from there) are hidden somewhere deep in the python root (in Linux: ``/usr/bin/pythonXX``), though I don't remember the exact file. Maybe your flag is added somewhere there, too.

What exactly do you try do do in the linked travis build? AFAIK, travis builds are only for Linux versions, and when I have a closer look into the build, line 11 says: ``export DEBIAN_FRONTEND=noninteractive``, so I assume that we have a Debian system. However, it seems that you want to compile with a MacOSX compiler. Maybe this cross-compilation approach is not ideal.

Anyways, if nothing else helps, maybe you can have a hack like this:
https://github.com/bioidiap/bob.extension/blob/master/bob/extension/__init__.py#L623
where I filter out one of the default compiler options (``-Wstrict-prototypes``) which is only valid for C compilers, and which was generating a lot of warning messages during our C++ builds. It seems that NumPy builds do the same thing... (see e.g. ``/usr/lib/python2.7/dist-packages/numpy/distutils/ccompiler.py``)

**Comment by 183amir** [comment]
That is in fact a mac machine even though it says `export DEBIAN_FRONTEND=noninteractive`.
Conda does set some [environment variables](http://conda.pydata.org/docs/building/environment-vars.html#environment-variables-set-during-the-build-process).
I fixed the problem with setting the `MACOSX_DEPLOYMENT_TARGET=10.7` environment variable.
Now it is failing with another reason that I do not know why: https://travis-ci.org/conda-forge/staged-recipes/builds/121967138
But that's another issue and I will close this.
